much cleaner

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,12 +1,12 @@
-#/bin/bash
+#!/usr/bin/env bash
 
 # run kvm v01 alpha
 # by @danalec
 
 #### config ####
 
-USERNAME=$USER
-GROUP="users"
+IMG=$HOME/.win.img
+OVMF=$HOME/kvm/ovmf_x64.bin
 
 VMNAME="windows"
 MEMORY=8
@@ -18,7 +18,7 @@ THREADS=2
 USB[0]="Razer"
 USB[1]="Holtek"
 
-# PCI-E Passthrough
+# PCI-E Passthrough (iommu group)
 PCI[0]="0000:01:00.0"
 PCI[1]="0000:01:00.1"
 PCI[2]="0000:09:00.0"
@@ -34,6 +34,8 @@ KEYBOARD="us alt-intl"
 IP="192.168.1.3"
 PORT="24800"
 
+SUDO_UID=$(whoami)
+SUDO_GID="users"
 #### end of config ####
 
 ## before-qemu tasks ##
@@ -59,6 +61,13 @@ else
 fi
 ## end of before-qemu tasks ##
 
+BDF_REGEX="^[[:xdigit:]]{2}:[[:xdigit:]]{2}.[[:xdigit:]]$"
+DBDF_REGEX="^[[:xdigit:]]{4}:[[:xdigit:]]{2}:[[:xdigit:]]{2}.[[:xdigit:]]$"
+
+if [[ ! $EUID -ne 0 ]]; then
+    echo "This script cannot be run as root" 1>&2
+    exit 1
+fi
 
 ##ascii
 echo ""
@@ -74,8 +83,6 @@ for i in {16..35} {35..16} ; do echo -en "\e[38;5;${i}m-\e[0m" ; done ; echo
 echo -e "\e[92m"
 ##end of ascii
 
-chmod +x $HOME/kvm/vfio # must be executable
-
 #### root required ####
 echo "checking /etc/modprobe.d/kvm.conf ..."
 if [ ! -f "/etc/modprobe.d/kvm.conf" ]; then
@@ -90,20 +97,7 @@ if [ ! -f "/etc/modprobe.d/vfio.conf" ]; then
   sudo touch /etc/modprobe.d/vfio.conf
   echo "writing to the new vfio.conf..."
   echo 'options vfio_iommu_type1 allow_unsafe_interrupts=1' | sudo tee --append /etc/modprobe.d/vfio.conf
-  #todo
-  echo 'options vfio-pci ids=10de:1c02,10de:10f1' | sudo tee --append /etc/modprobe.d/vfio.conf
 fi
-
-for PCI_DEVICE in "${PCI[@]}"
-do
-  echo "binding..."
-  vendor=$(sudo cat /sys/bus/pci/devices/$PCI_DEVICE/vendor)
-  device=$(sudo cat /sys/bus/pci/devices/$PCI_DEVICE/device)
-  if [ -e /sys/bus/pci/devices/$PCI_DEVICE/driver ]; then
-    echo $PCI_DEVICE | sudo tee --append /sys/bus/pci/devices/$PCI_DEVICE/driver/unbind
-  fi
-  echo $vendor $device | sudo tee --append /sys/bus/pci/drivers/vfio-pci/new_id
-done
 
 echo "setting hugepages..."
 sudo sysctl -w vm.nr_hugepages=$(expr $MEMORY \* 512)
@@ -113,11 +107,8 @@ echo "checking if hugepages folder exists..."
 if [ ! -d "/dev/hugepages/qemu" ]; then
   echo "creating a new hugepages folder..."
   sudo mkdir /dev/hugepages/qemu
-  sudo chown $USERNAME:$GROUP /dev/hugepages/qemu
+  sudo chown $SUDO_UID:$SUDO_GID "/dev/hugepages/qemu"
 fi
-
-echo "grant permissions for vfio..."
-sudo chown $USERNAME:$GROUP /dev/vfio/*
 
 echo "probing vfio..."
 sudo modprobe vfio
@@ -131,6 +122,7 @@ if [[ $? -ne 0 ]]; then
     echo -e "\e[36merror probing vfio-pci"
     exit 1
 fi
+
 echo "probing vfio_iommu_type1..."
 sudo modprobe vfio_iommu_type1
 if [[ $? -ne 0 ]]; then
@@ -143,17 +135,30 @@ if [[ $? -ne 0 ]]; then
     echo -e "\e[36merror probing vfio_virqfd"
     exit 1
 fi
-sleep 1
+
+for PCI_DEVICE in "${PCI[@]}"
+do
+  echo "binding..."
+  vendor=$(sudo cat /sys/bus/pci/devices/$PCI_DEVICE/vendor)
+  device=$(sudo cat /sys/bus/pci/devices/$PCI_DEVICE/device)
+  if [ -e /sys/bus/pci/devices/$PCI_DEVICE/driver ]; then
+    echo $PCI_DEVICE | sudo tee --append /sys/bus/pci/devices/$PCI_DEVICE/driver/unbind
+  fi
+  echo $vendor $device | sudo tee --append /sys/bus/pci/drivers/vfio-pci/new_id
+done
+
+echo "grant permissions for vfio..."
+sudo chown $SUDO_UID:$SUDO_GID /dev/vfio/*
 
 #echo "setting tuntap device..."
-#sudo tunctl -t tap0 -u danalec -g users
-#sudo chown $USERNAME:$GROUP /dev/net/tun
+#sudo tunctl -t tap0 -u $SUDO_UID -g $SUDO_GID
+#sudo chown $SUDO_UID:$SUDO_GID /dev/net/tun
 #sudo chmod 755 /dev/net/
 
 for grep in "${USB[@]}"
 do
    echo "grant permissions for"$(lsusb | grep $grep | awk '{$1=$2=$3=$4=$5=$6=""; print $0}')
-   lsusb | grep $grep | awk '{ system ("sudo chown '$USERNAME':'$GROUP' /dev/bus/usb/"$2"/"substr($4, 1, length($4)-1)) }'
+   lsusb | grep $grep | awk '{ system ("sudo chown '$SUDO_UID':'$SUDO_GID' /dev/bus/usb/"$2"/"substr($4, 1, length($4)-1)) }'
 done
 #### end of required root ####
 
@@ -188,7 +193,7 @@ D=""
 D="$D -name $VMNAME,process=$VMNAME"
 
 # CPU
-D="$D -machine pc,kernel_irqchip=on,mem-merge=off"
+D="$D -machine pc,kernel_irqchip=on,mem-merge=off,accel=kvm"
 D="$D -cpu host,kvm=off,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time,hv_vendor_id=whatever"
 D="$D -smp $SMP,cores=$CORES,threads=$THREADS"
 D="$D -rtc base=localtime,clock=host"
@@ -226,14 +231,14 @@ D="$D -serial none -parallel none -balloon none" #misc
 
 # Supply OVMF (general UEFI bios, needed for EFI boot support with GPT disks)
 # pacaur -S ovmf-git && cp /usr/share/ovmf/x64/ovmf_x64.bin $HOME/kvm/ovmf_x64.bin
-D="$D -drive if=pflash,format=raw,readonly,file=$HOME/kvm/ovmf_x64.bin"
+D="$D -drive if=pflash,format=raw,readonly,file=$OVMF"
 
-# Controllers
-D="$D -device virtio-scsi-pci,id=scsi" # load virtio SCSI controller
+# load virtio SCSI controller
+D="$D -device virtio-scsi-pci,id=scsi"
 
 # Load VM image as a harddrive
 # to create an image: qemu-img create -f qcow2 -o preallocation=metadata win.img 120G
-D="$D -drive file=$HOME/kvm/win.img,id=disk,format=qcow2,if=none,cache=writeback -device scsi-hd,drive=disk"
+D="$D -drive file=$IMG,id=disk,format=qcow2,if=none,cache=writeback -device scsi-hd,drive=disk"
 
 # Load our OS setup image and drivers ISO
 #wget https://fedorapeople.org/GROUPs/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.133-1/virtio-win-0.1.133.iso
@@ -241,6 +246,7 @@ D="$D -drive file=$HOME/kvm/win.img,id=disk,format=qcow2,if=none,cache=writeback
 #D="$D -drive file=$HOME/kvm/Win10_1607_N_English_x64.iso,id=isocd,format=raw,if=none -device scsi-cd,drive=isocd"
 
 #D="$D -net nic,model=virtio -net tap,ifname=tap0,script=no,downscript=no" # network
+D="$D -net none"
 
 qemu-system-x86_64 $D
 
@@ -258,8 +264,6 @@ if [ -f "/usr/bin/synergy" ]; then
   fi
 fi
 
-
-
 # us alt-intl restore
 echo ""
 if [ "$altintl" == "1" ]; then
@@ -270,3 +274,7 @@ fi
 # turn monitor 2 on again
 xrandr --output HDMI-2 --auto
 xrandr --output HDMI-2 --right-of HDMI-1
+
+# destroy hugepages
+echo "setting hugepages zero"
+sudo sysctl -w vm.nr_hugepages=0
